### ISSUE TITLE
AWA2.mat

### ISSUE THREAD

**Issue by Enrinz** [vkkhare/ZSL-ADA#2]
Where could i find AWA2.mat? 
I know AWA2 as a directory, not a .mat file

thanks

**Comment by vkkhare** [comment]
Hey AWA2.mat is just holding the data extracted from the awa. Let me see if I have the mat file kept somewhere

**Comment by Enrinz** [comment]
It would be very helpful, thanks

**Comment by divyat09** [comment]
@Enrinz You can access the dataset files from here: https://1drv.ms/u/s!Am4PEeFsC-8thw8jg8Iq8-D20Sul?e=db0zAa

**Comment by Enrinz** [comment]
Many thanks!
